// califaicon.cpp
// Icono califa en formato XPM

const char * califa_icon[] = {
    "46 29 6 1",
    ". c None",
    "# c #000000",
    "b c #ff0000",
    "a c #ffff00",
    "c c #ffff80",
    "d c #ffffff",
    "..............................................",
    ".##................########................##.",
    ".#a##......########bbbbbbbb######.......###c#.",
    ".#aaa######bbbbbbbbbbbbbbbbbbbbbb####.##cccc#.",
    "..#aaaaa###bbbbbbbbbbbbbbbbbbbbbbbb###ccccc#..",
    "..#aaaaaaaa##bbbbbbbbbbbbbbbbbbb###cccccccc#..",
    "..#aaaaaaaaaa###bbbbbbbbbbbbb####cccccccccc#..",
    "..#aaaaaaaaaaaaa###bbbbbbbb##aaaa######cccc#..",
    "..####aaaaaaaaaaaaa##bbb###aaaaaaaaaaaa###c#..",
    "..#aaa#####aaaaaaaaaa###aaaaaaaaaaaaaaaa###...",
    "...#aaaaaaa#####aaaaaaaaaaaaaaaaaaaa####aa#...",
    "...#aaaaaa##cccc####aaaaaaaaaaaa####aaaaaa#...",
    "...#aaaa##cccccccccc###aaaaaa###aaaaaaaaaa#...",
    "...##a##ccccccccccccccc######aaaaaaaaaaaaa#...",
    "...#d###ccccccccccccc####aaaaaaaaaaaaaa###....",
    "....#ccc####ccccc####aaaaaaaaaaaaaa####cc#....",
    "....#ccccccc#####aaaaaaaaaaaaaaa###cc##cc#....",
    "....###cccccccc###aaaaaaaaaaa###ccccccc###....",
    "....#cc###cccccccc###aaaa####ccccccccccc##....",
    "....#ccccc###cccccccc####ccccccccccccc###.....",
    "....#cccccccc###ccccccccc###ccccccc###aa#.....",
    "....#ccccccccccc###ccccccccc##c####c##aa#.....",
    ".....#cccccccccc##a###cccccc###ccccccc#a#.....",
    ".....##cccccc###aaaaaa###c##ccccccccccc##.....",
    ".....#c###c##aaaaaaaaaaaa###ccccccccccc#......",
    ".....#cccc##aaaaaaaaaaaaaaaa###cccccccc#......",
    "......#ccccc###aaaaaaaaaaaaaaaa##cccccc#......",
    "......##################################......",
    ".............................................."
};
