// generated 2006/1/9 12:38:31 CET by baltasarq@pcjgarcia.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/baltasarq/prys/Califa/Califa.glade
// for gtk 2.8.6 and gtkmm 2.8.0
//
// Please modify the corresponding derived classes in ./src/ventanappal.h and./src/VentanaPpal.cc

#ifndef _VENTANAPPAL_GLADE_HH
#define _VENTANAPPAL_GLADE_HH

#include <gtkmm/window.h>
#include <gtkmm/menubar.h>
#include <gtkmm/toolbutton.h>
#include <gtkmm/treeview.h>
#include <gtkmm/statusbar.h>
#include <gtkmm/menu.h>
#include <gtkmm/imagemenuitem.h>
#include <gtkmm/menuitem.h>

class VentanaPpal_glade : public Gtk::Window {
public:
         Gtk::Window * VentanaPpal;
         Gtk::MenuBar * menubar1;
         Gtk::ToolButton * botBarraGuardar;
         Gtk::ToolButton * botBarraBuscar;
         Gtk::ToolButton * botBarraAscendente;
         Gtk::ToolButton * botBarraDescendente;
		 Gtk::ToolButton * botBarraInsertarEnMedio;
         Gtk::ToolButton * botBarraInsertar;
         Gtk::ToolButton * botBarraBorrar;
         Gtk::ToolButton * botBarraPropiedades;
         Gtk::ToolButton * botBarraConvertir;
         Gtk::TreeView * tablaCalifas;
         Gtk::Statusbar * barraEstado;
protected:

        VentanaPpal_glade();
        ~VentanaPpal_glade();

		Gtk::ImageMenuItem *opInsertarEnMedio;
	   	Gtk::ImageMenuItem *opGuardar;
   		Gtk::ImageMenuItem *opGuardarComo;
   		Gtk::ImageMenuItem *opCerrar;
   		Gtk::ImageMenuItem *opConvertir;
   		Gtk::ImageMenuItem *opMezclar;
		Gtk::MenuItem *opConvertirParComa;
		Gtk::MenuItem *opConvertirDeParComa;
		Gtk::MenuItem *opVerificarDNIs;
		Gtk::Menu *menuEditar;
		Gtk::Menu *menuHerramientas;

private:
        virtual void on_nuevo1_activate() = 0;
        virtual void on_opCerrar_activate() = 0;
        virtual void on_abrir1_activate() = 0;
        virtual void on_opMezclar_activate() = 0;
        virtual void on_opGuardar_activate() = 0;
        virtual void on_opGuardarComo_activate() = 0;
        virtual void on_importar1_activate() = 0;
        virtual void on_opConvertir_activate() = 0;
        virtual void on_salir1_activate() = 0;
        virtual void on_borrar1_activate() = 0;
        virtual void on_a__adir1_activate() = 0;
        virtual void on_stats_activate() = 0;
        virtual void on_rellenar_activate() = 0;
        virtual void on_ascendente1_activate() = 0;
        virtual void on_descendente1_activate() = 0;
        virtual void on_buscar1_activate() = 0;
        virtual void on_propiedades1_activate() = 0;
        virtual void on_informaci__n1_activate() = 0;
        virtual void on_acerca_de1_activate() = 0;
        virtual void on_insertar_en_medio_activate() = 0;
		virtual void on_buscar_de_nuevo1_activate() = 0;
		virtual void on_verificar_dnis_activate() = 0;
		virtual void on_convertirNombreAParComa_activate() = 0;
		virtual void on_convertirNombreDeParComa_activate() = 0;

};
#endif
